// export enum VisType {
//   Area = 'area',
//   Bar = 'bar',
//   Column = 'column',
//   DualAxes = 'dual-axes',
//   FishboneDiagram = 'fishbone-diagram',
//   FlowDiagram = 'flow-diagram',
//   Histogram = 'histogram',
//   Line = 'line',
//   MindMap = 'mind-map',
//   NetworkGraph = 'network-graph',
//   Pie = 'pie',
//   Radar = 'radar',
//   Scatter = 'scatter',
//   Treemap = 'treemap',
//   WordCloud = 'word-cloud',
// }
