name: CI

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - '__tests__/**'
  pull_request:
    branches:
      - '**'
    paths:
      - 'src/**'
      - '__tests__/**'
      - 'evaluations/**'
      - 'knowledges/**'
      - 'docs/**'

permissions:
  contents: read # to fetch code (actions/checkout)

concurrency:
  group: '${{ github.workflow }} - ${{ github.ref }}'
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/prepare-install
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check
        run: |
          pnpm check-deps
          pnpm check-format
      - name: Lint
        run: pnpm lint:ts

  # unit-test:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [18.x]
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install dependencies
  #       uses: ./.github/actions/prepare-install
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     - name: Unit Test
  #       run: pnpm test:unit

  size-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/prepare-install
        with:
          node-version: ${{ matrix.node-version }}
      - name: Size Test With Build
        run: pnpm test:size

  ssr-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: cd bindings/gpt-vis-ssr && npm install
      - name: Test & Build
        run: cd bindings/gpt-vis-ssr && npm run test && npm run build
      - name: Upload blob report to GitHub Actions Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: snapshots
          path: |
            bindings/gpt-vis-ssr/__tests__/snapshot/**/*-actual.png
          retention-days: 1
